### PR TITLE
Add DisplayN18 Module

### PR DESCRIPTION
**Pull request by bauland**
Update README.md with current list of modules
Add ignore folders/files to remove binary files which been updated at each rebuild operation

### CODE REVIEW

**Comment by bauland** [comment]
My contribution ...

**Comment by mifmasterz** [comment]
Thanks

**Review by mifmasterz — APPROVED** [review]
Ok

**Review by mifmasterz — APPROVED** [review]
Ok

**Review by mifmasterz — APPROVED** [review]
Ok

**Pull request merged**
